export FOX_BUILD_DEVICE=LG6n
export FOX_AB_DEVICE=1
export FOX_VANILLA_BUILD=1
export FOX_USE_NANO_EDITOR=1
export OF_MAINTAINER="Nomi"
export ALLOW_MISSING_DEPENDENCIES=true
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
